DROP DATABASE IF EXISTS project2;
CREATE DATABASE project2;
USE project2; 


CREATE TABLE gifs
(
  gif_ID INT NOT NULL AUTO_INCREMENT, 
  url VARCHAR(500),
  wins INTEGER,
  PRIMARY KEY (gif_Id)
);

CREATE TABLE favorites
(
id INT NOT NULL AUTO_INCREMENT, 
url VARCHAR(500),
PRIMARY KEY (id)
);

CREATE TABLE users
(
id INT NOT NULL AUTO_INCREMENT, 
email VARCHAR(500),
password VARCHAR(500),
firstName VARCHAR(500),
lastName VARCHAR(500),
wins INTEGER,
PRIMARY KEY (id)
);