DROP DATABASE IF EXISTS project2;
CREATE DATABASE project2;
USE project2; 


CREATE TABLE gifs
(
  gif_ID INT NOT NULL AUTO_INCREMENT, 
  url VARCHAR(500),
  wins INTEGER,
  PRIMARY KEY (gif_Id)
);

SELECT * FROM gifs;
